-- Execute once in the Supabase SQL Editor. Never execute SQL from the browser.
-- OTP verification, expiration, replay checks and rate limits are handled by Supabase Auth.
-- Configure an EMAIL OTP template containing {{ .Token }} and verified SMTP.
create table if not exists public.profiles (
 id uuid primary key references auth.users(id) on delete cascade,
 display_name text not null default '' check (char_length(display_name)<=32),
 avatar_path text not null default '' check (char_length(avatar_path)<=250),
 updated_at timestamptz not null default now()
);
create or replace function public.on_new_user()
returns trigger language plpgsql security definer set search_path = ''
as $$
 begin
  insert into public.profiles(id) values (new.id) on conflict(id) do nothing;
  return new;
 end;
$$;
drop trigger if exists create_zer0game_profile on auth.users;
create trigger create_zer0game_profile after insert on auth.users for each row execute function public.on_new_user();
alter table public.profiles enable row level security;
drop policy if exists "Read own profile" on public.profiles;
create policy "Read own profile" on public.profiles for select to authenticated using ((select auth.uid())=id);
drop policy if exists "Insert own profile" on public.profiles;
create policy "Insert own profile" on public.profiles for insert to authenticated with check ((select auth.uid())=id);
drop policy if exists "Update own profile" on public.profiles;
create policy "Update own profile" on public.profiles for update to authenticated using ((select auth.uid())=id) with check ((select auth.uid())=id);
create table if not exists public.favorites (
 user_id uuid not null references auth.users(id) on delete cascade,
 game_key text not null check (char_length(game_key) between 1 and 180),
 game_title text not null default '' check (char_length(game_title)<=180),
 created_at timestamptz not null default now(),
 primary key(user_id,game_key)
);
alter table public.favorites enable row level security;
drop policy if exists "Own favorites select" on public.favorites;
create policy "Own favorites select" on public.favorites for select to authenticated using (user_id=(select auth.uid()));
drop policy if exists "Own favorites insert" on public.favorites;
create policy "Own favorites insert" on public.favorites for insert to authenticated with check (user_id=(select auth.uid()));
drop policy if exists "Own favorites delete" on public.favorites;
create policy "Own favorites delete" on public.favorites for delete to authenticated using (user_id=(select auth.uid()));
create table if not exists public.activity_events (
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 action text not null check (action in ('search_game','search_cheat','view_game','download_game','download_dlc','download_cheat')),
 game_title text not null default '' check (char_length(game_title)<=180),
 title_id text not null default '' check (char_length(title_id)<=48),
 search_query text not null default '' check (char_length(search_query)<=180),
 created_at timestamptz not null default now()
);
create index if not exists activity_events_user_time on public.activity_events(user_id,created_at desc);
alter table public.activity_events enable row level security;
drop policy if exists "Own activity select" on public.activity_events;
create policy "Own activity select" on public.activity_events for select to authenticated using (user_id=(select auth.uid()));
drop policy if exists "Own activity insert" on public.activity_events;
create policy "Own activity insert" on public.activity_events for insert to authenticated with check (user_id=(select auth.uid()));
drop policy if exists "Own activity delete" on public.activity_events;
create policy "Own activity delete" on public.activity_events for delete to authenticated using (user_id=(select auth.uid()));
-- No anonymous profile/activity/favorites access, no admin role columns, no broad policies.
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types)
 values ('avatars','avatars',true,2097152,array['image/jpeg','image/png','image/webp'])
 on conflict(id) do update set file_size_limit=excluded.file_size_limit,
 allowed_mime_types=excluded.allowed_mime_types;
drop policy if exists "Upload avatar into own folder" on storage.objects;
create policy "Upload avatar into own folder" on storage.objects for insert to authenticated
 with check (bucket_id='avatars' and (storage.foldername(name))[1]=(select auth.uid())::text);
drop policy if exists "Delete own avatars" on storage.objects;
create policy "Delete own avatars" on storage.objects for delete to authenticated
 using (bucket_id='avatars' and (storage.foldername(name))[1]=(select auth.uid())::text);
-- Public read is intentional for displayable avatars; only authenticated users can upload.
